### PR TITLE
Fixed realtime monitor 

### PR DESCRIPTION
**Pull request by eoghan2t9**
Fixed realtime monitor with the help of chatgpt and it now runs for me plus runs in the background detecting in full realtime

### CODE REVIEW

**Comment by sureshfizzy** [comment]
Let me test this and merge, some changes looks odd to me.

**Comment by sureshfizzy** [comment]
https://github.com/sureshfizzy/CineSync/pull/6/commits/a7dab330ea916759adc8b21ed9eaaa9423495c7e#diff-5990676dae026aef7627bec042def91dfefb2ec578702af4be421e156cfa59feR68

This causes execution to fail on Windows, as it is unable to decrypt properly and throws a Unicode error. It also breaches another condition, if the destination directory is empty, the script will fail to run.

Running on Windows
OS Version: 10.0.19045
Found watch directory in script: D:\Watch
Found destination directory in script: D:\Watch\Sample
Watching directory: D:\Watch
Destination directory: D:\Watch\Sample
Starting initial scan...
Initial files in watch directory: set()
Error: Destination directory is empty.

**Comment by eoghan2t9** [comment]
I shall have a look at that today and see what's the cause of that is on windows

**Comment by sureshfizzy** [comment]
I'm trying to figure out what went wrong on your end but haven't got time due to office works ☹️. I'll sit on it later on and see this issue.

**Pull request closed without merging**
